<?php
$userlist = "<div class='adminUser'>";
$userlist .= "<div><a href='/admin/user/create'>create new user</a></div>";
$userlist .= "<table class='userList'>";
$userlist .= "<tr class='userLine'>".
	"<th class='role'>Role</th>".
	"<th class='userName'>Username</th>".
	"<th class='email'>Email</th>".
	"<th class='firstName'>First Name</th>".
	"<th class='surName'>Last Name</th>".
	"<th class='controls' colspan=2></th>".
	"</tr>";
$userlist .= $this->partialLoop('partials/userlist.phtml', $this->userlist);
$userlist .= "</table>";
$userlist .= "</div>";
echo $userlist;

