<?php
$newsItemDetail = "<div class='newsItemDetail'>";
$newsItemDetail .= "<div class='newsItemTitlebar'>".
	"<div class='title'>".$this->detail['title']."</div>".
	"<div class='author'>".$this->detail['firstName'].' '.$this->detail['surName']."</div>".
	"<div class='date'>".$this->date($this->detail['postTime'])."</div>".
	"</div>";
$newsItemDetail .= "<div class='content'>".nl2br($this->detail['content'])."</div>";
$newsItemDetail .= "</div>";
echo $newsItemDetail;

$newsItemComments = "<div class='newsItemComments'>";

$newsItemComments .= "<div class='newsItemNewComment'>";
$newsItemComments .= "<div class='title'>Add a new comment</div>";
$newsItemComments .= $this->form;
$newsItemComments .= "</div>";
$newsItemComments .= "</div>";
echo $newsItemComments;
