<?php
$userline = "<tr class='userLine'>".
	"<td class='role'>".$this->role."</td>".
	"<td class='userName'>".$this->userName."</td>".
	"<td class='email'>".$this->email."</td>".
	"<td class='firstName'>".$this->firstName."</td>".
	"<td class='surName'>".$this->surName."</td>".
	"<td class='controls'><a href='/admin/user/edit/id/".$this->id."'>edit</a></td>".
	"<td class='controls'><a href='/admin/user/delete/id/".$this->id."'>delete</a></td>".
	"</tr>";
echo $userline;
