<tr class='userLine'>
<td class='role'><?php echo $this->role; ?></td>
<td class='userName'><?php echo $this->userName; ?></td>
<td class='email'><?php echo $this->email; ?></td>
<td class='firstName'><?php echo $this->firstName; ?></td>
<td class='surName'><?php echo $this->surName; ?></td>
<td class='edit'><a href='/admin/user/edit/id/<?php echo $this->id; ?>'>edit</a></td>
<td class='delete'><a href='/admin/user/delete/id/<?php echo $this->id; ?>'>delete</a></td>
</tr>