<?php
//$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('BruneauNews');

echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headTitle(); ?>
	<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/brunews.css'); ?>
</head>
<body>
	<div id="content">
		<?php echo $this->layout()->content; ?>
	</div>
	<div id="login">
		<?php echo $this->placeholder('login'); ?>
	</div>
	<div id='messages'>
		<?php echo Zend_Debug::dump($this->messages); ?>
	</div>
</body>
</html>
